Using inputs.target-arch avoid mismatches if reused for cross-arch builds

diff --git a/.github/actions/build-okd/action.yaml b/.github/actions/build-okd/action.yaml
--- a/.github/actions/build-okd/action.yaml
+++ b/.github/actions/build-okd/action.yaml
@@ -34,7 +34,7 @@ runs:
       uses: ./.github/actions/arch
 
     - name: Collect debug information before the build
-      if: ${{ always() }}
+      if: always()
       uses: ./.github/actions/debug-info
 
     - name: Prepare the build and run environment
@@ -45,7 +45,7 @@ runs:
       with:
         token: ${{ inputs.token }}
 
-    - name: Build OKD images
+    - name: Build and push OKD images to staging registry
       shell: bash
       run: |
         set -euo pipefail
@@ -73,10 +73,12 @@ runs:
         STAGING_REGISTRY="$(dirname "${PRODUCTION_REGISTRY}")/okd-staging"
 
         # Set the correct architecture-specific variable for staging override
-        if [ "${{ steps.detect-cpu-arch.outputs.go_arch }}" = "arm64" ]; then
+        if [ "${{ inputs.target-arch }}" = "arm64" ]; then
           OKD_OVERRIDE="OKD_RELEASE_IMAGE_AARCH64=${STAGING_REGISTRY}/okd-release-arm64"
-        else
+        elif [ "${{ inputs.target-arch }}" = "amd64" ]; then
           OKD_OVERRIDE="OKD_RELEASE_IMAGE_X86_64=${STAGING_REGISTRY}/okd-release-amd64"
+        else
+          echo "ERROR: Unsupported target-arch: ${{ inputs.target-arch }}" ; exit 1
         fi
 
         make rpm \
@@ -113,7 +115,7 @@ runs:
         make stop
 
     - name: Push OKD images to production registry
-      if: ${{ success() }}
+      if: success()
       shell: bash
       run: |
         set -euo pipefail
@@ -133,9 +135,9 @@ runs:
     #   uses: ./.github/actions/tmate-debug
 
     - name: Collect debug information after the build
-      if: ${{ always() }}
+      if: always()
       uses: ./.github/actions/debug-info
 
     - name: Collect MicroShift container sos-report on failure
-      if: ${{ failure() }}
+      if: failure()
       uses: ./.github/actions/sos-report
