Verify no Internet access in offline mode

diff --git a/.github/actions/build/action.yaml b/.github/actions/build/action.yaml
--- a/.github/actions/build/action.yaml
+++ b/.github/actions/build/action.yaml
@@ -108,6 +108,17 @@ runs:
         # Run the MicroShift container
         make run ${make_opts[@]}
 
+        # Verify that Internet access is not available in the container
+        # when the isolated network is enabled
+        if [ "${{ inputs.isolated-network }}" = "1" ]; then
+          for cmd in "ping -c1 8.8.8.8" "curl -I quay.io" "curl -I ghcr.io"; do
+            if sudo podman exec -i microshift-okd ${cmd} ; then
+              echo "Error: Internet access is available in the isolated network container"
+              exit 1
+            fi
+          done
+        fi
+
         # Wait until the MicroShift service is ready and healthy
         make run-ready
         make run-healthy
